In [2]:
# Render our plots inline
%matplotlib inline
 
import pandas as pd
import matplotlib.pyplot as plt
import random

optimalFrame = pd.read_csv('./data/trace1/optimalSetTrace1.csv', encoding="utf-8", header=0, sep=',', index_col=0)
optimalFrame.head(5)

,srcip,srcport,dstip,dstport,proto,total_fpackets,total_fvolume,total_bpackets,total_bvolume,min_fpktl,...,sflow_fbytes,sflow_bpackets,sflow_bbytes,fpsh_cnt,bpsh_cnt,furg_cnt,burg_cnt,total_fhlen,total_bhlen,label
0,150.193.9.119,36194,199.253.112.198,53,6,6,363,4,795,52,...,363,4,795,1,1,0,0,320,216,dns
1,133.180.64.216,34049,202.252.24.239,53,6,6,350,4,1319,52,...,350,4,1319,1,1,0,0,320,220,dns
2,203.141.113.140,48631,194.178.73.34,53,6,6,379,4,1162,52,...,379,4,1162,1,1,0,0,320,216,dns
3,133.154.140.225,42868,202.252.24.239,53,6,6,367,4,1139,52,...,367,4,1139,1,1,0,0,320,220,dns
4,150.193.9.119,44855,204.123.216.116,53,6,6,365,4,990,52,...,365,4,990,1,1,0,0,320,216,dns

In [3]:
optimalFrame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3363 entries, 0 to 3362
Data columns (total 45 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   srcip           3363 non-null   object
 1   srcport         3363 non-null   int64
 2   dstip           3363 non-null   object
 3   dstport         3363 non-null   int64
 4   proto           3363 non-null   int64
 5   total_fpackets  3363 non-null   int64
 6   total_fvolume   3363 non-null   int64
 7   total_bpackets  3363 non-null   int64
 8   total_bvolume   3363 non-null   int64
 9   min_fpktl       3363 non-null   int64
 10  mean_fpktl      3363 non-null   int64
 11  max_fpktl       3363 non-null   int64
 12  std_fpktl       3363 non-null   int64
 13  min_bpktl       3363 non-null   int64
 14  mean_bpktl      3363 non-null   int64
 15  max_bpktl       3363 non-null   int64
 16  std_bpktl       3363 non-null   int64
 17  min_fiat        3363 non-null   int64
 18  mean_fiat       3363 non-null   int64
 19  max_fiat        3363 non-null   int64
 20  std_fiat        3363 non-null   int64
 21  min_biat        3363 non-null   int64
 22  mean_biat       3363 non-null   int64
 23  max_biat        3363 non-null   int64
 24  std_biat        3363 non-null   int64
 25  duration        3363 non-null   int64
 26  min_active      3363 non-null   int64
 27  mean_active     3363 non-null   int64
 28  max_active      3363 non-null   int64
 29  std_active      3363 non-null   int64
 30  min_idle        3363 non-null   int64
 31  mean_idle       3363 non-null   int64
 32  max_idle        3363 non-null   int64
 33  std_idle        3363 non-null   int64
 34  sflow_fpackets  3363 non-null   int64
 35  sflow_fbytes    3363 non-null   int64
 36  sflow_bpackets  3363 non-null   int64
 37  sflow_bbytes    3363 non-null   int64
 38  fpsh_cnt        3363 non-null   int64
 39  bpsh_cnt        3363 non-null   int64
 40  furg_cnt        3363 non-null   int64
 41  burg_cnt        3363 non-null   int64
 42  total_fhlen     3363 non-null   int64
 43  total_bhlen     3363 non-null   int64
 44  label           3363 non-null   object
dtypes: int64(42), object(3)
memory usage: 1.2+ MB

In [3]:
optimalFrame['duration']

0         28587
1         44833
2        289691
3         40886
4         27595
         ...
3358    6274228
3359     469592
3360    1285548
3361    5456159
3362    8821409
Name: duration, Length: 3363, dtype: int64

In [4]:
optimalFrame.index.name = "index"

In [5]:
optimalFrame.head(5)

,srcip,srcport,dstip,dstport,proto,total_fpackets,total_fvolume,total_bpackets,total_bvolume,min_fpktl,...,sflow_fbytes,sflow_bpackets,sflow_bbytes,fpsh_cnt,bpsh_cnt,furg_cnt,burg_cnt,total_fhlen,total_bhlen,label
index,,,,,,,,,,,,,,,,,,,,,
0,150.193.9.119,36194,199.253.112.198,53,6,6,363,4,795,52,...,363,4,795,1,1,0,0,320,216,dns
1,133.180.64.216,34049,202.252.24.239,53,6,6,350,4,1319,52,...,350,4,1319,1,1,0,0,320,220,dns
2,203.141.113.140,48631,194.178.73.34,53,6,6,379,4,1162,52,...,379,4,1162,1,1,0,0,320,216,dns
3,133.154.140.225,42868,202.252.24.239,53,6,6,367,4,1139,52,...,367,4,1139,1,1,0,0,320,220,dns
4,150.193.9.119,44855,204.123.216.116,53,6,6,365,4,990,52,...,365,4,990,1,1,0,0,320,216,dns

In [6]:
autoClassTrainingData = optimalFrame[['mean_fpktl', 'mean_bpktl', 'mean_fiat', 'std_fpktl', 'std_bpktl']]

In [7]:
autoClassTrainingData.to_csv("data/trace1/sampleTrainingAutoclass.tsv", sep="\t", header=True)

In [1]:

from pathlib import Path
import sys
import time

import matplotlib
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd

%matplotlib inline

print("Python:", sys.version)
print("matplotlib:", matplotlib.__version__)
print("numpy:", np.__version__)
print("pandas:", pd.__version__)

import autoclasswrapper as wrapper
print("AutoClassWrapper:", wrapper.__version__)

version = sys.version_info
if not ((version.major >= 3) and (version.minor >= 6)):
    sys.exit("Need Python>=3.6")

Python: 3.7.5 (default, Nov 20 2019, 09:21:52)
[GCC 9.2.1 20191008]
matplotlib: 3.2.1
numpy: 1.18.2
pandas: 1.0.3
AutoClassWrapper: 1.5.1

In [1]:
# Create object to prepare dataset.
clust = wrapper.Input()

# Load datasets from tsv files.
clust.add_input_data("data/trace1/sampleTrainingAutoclass.tsv", "real scalar")

# Prepare input data:
# - create a final dataframe
# - merge datasets if multiple inputs
clust.prepare_input_data()

# Create files needed by AutoClass.
clust.create_db2_file()
clust.create_hd2_file()
clust.create_model_file()
clust.create_sparams_file(max_duration = 0)
clust.create_rparams_file()

NameError: name 'wrapper' is not defined

In [3]:
# Search autoclass in path.
wrapper.search_autoclass_in_path()

# Create object to run AutoClass.
run = wrapper.Run()

# Prepare run script.
run.create_run_file()

# Run AutoClass.
run.run()

2020-04-13 02:14:23 INFO     AutoClass C executable found in /home/chuongdv/Documents/SourceCode/MachineLearning/autoclass-c/autoclass
2020-04-13 02:14:23 INFO     Writing run file
2020-04-13 02:14:23 INFO     AutoClass C executable found in /home/chuongdv/Documents/SourceCode/MachineLearning/autoclass-c/autoclass
2020-04-13 02:14:23 INFO     AutoClass C version: AUTOCLASS C (version 3.3.6unx)
2020-04-13 02:14:23 INFO     Running clustering...

In [4]:
timer = 0
step = 2
while not Path("autoclass-run-success").exists():
    timer += step
    sys.stdout.write("\r")
    sys.stdout.write(f"Time: {timer} sec.")
    sys.stdout.flush()
    time.sleep(step)

results = wrapper.Output()
results.extract_results()
results.aggregate_input_data()
results.write_cdt()
results.write_cdt(with_proba=True)
results.write_class_stats()
results.write_dendrogram()

2020-04-13 02:27:16 INFO     Extracting autoclass results
2020-04-13 02:27:16 INFO     Found 3363 cases classified in 101 classes
2020-04-13 02:27:18 INFO     Aggregating input data
2020-04-13 02:27:18 INFO     Writing classes + probabilities .tsv file
2020-04-13 02:27:18 INFO     Writing .cdt file
2020-04-13 02:27:19 ERROR    Unknown format code 'd' for object of type 'float'

In [6]:
result = pd.read_csv('autoclass_out.tsv', encoding="utf-8", header=0, sep='\t', index_col=0)
result.head(5)

,mean_fpktl,mean_bpktl,mean_fiat,std_fpktl,std_bpktl,main-class,main-class-proba,class-1-proba,class-2-proba,class-3-proba,...,class-92-proba,class-93-proba,class-94-proba,class-95-proba,class-96-proba,class-97-proba,class-98-proba,class-99-proba,class-100-proba,class-101-proba
index,,,,,,,,,,,,,,,,,,,,,
0,60,198,5717,17,288,47,1.000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,58,329,8966,12,547,47,0.999,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,63,290,57938,23,471,47,1.000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,61,284,8177,18,457,47,1.000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,60,247,5519,18,385,47,1.000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3363 entries, 0 to 3362
Columns: 108 entries, mean_fpktl to class-101-proba
dtypes: float64(102), int64(6)
memory usage: 2.8 MB

In [7]:
optimalFrame['cluster'] = result['main-class']

In [8]:
optimalFrame.head(5)

,srcip,srcport,dstip,dstport,proto,total_fpackets,total_fvolume,total_bpackets,total_bvolume,min_fpktl,...,sflow_bpackets,sflow_bbytes,fpsh_cnt,bpsh_cnt,furg_cnt,burg_cnt,total_fhlen,total_bhlen,label,cluster
index,,,,,,,,,,,,,,,,,,,,,
0,150.193.9.119,36194,199.253.112.198,53,6,6,363,4,795,52,...,4,795,1,1,0,0,320,216,dns,47
1,133.180.64.216,34049,202.252.24.239,53,6,6,350,4,1319,52,...,4,1319,1,1,0,0,320,220,dns,47
2,203.141.113.140,48631,194.178.73.34,53,6,6,379,4,1162,52,...,4,1162,1,1,0,0,320,216,dns,47
3,133.154.140.225,42868,202.252.24.239,53,6,6,367,4,1139,52,...,4,1139,1,1,0,0,320,220,dns,47
4,150.193.9.119,44855,204.123.216.116,53,6,6,365,4,990,52,...,4,990,1,1,0,0,320,216,dns,47

In [9]:
optimalFrame.to_csv('./data/trace1/resultTrace1.csv', index = True)